### ISSUE TITLE
参数失效

### ISSUE THREAD

**Issue by angelas1qiaolezi** [Hellager/weibo_supertopic_sign#1]
![Screenshot_20210913_160802_com tencent mm](https://user-images.githubusercontent.com/90556379/133047488-cdf2b2d3-2701-4834-9fa3-6a5bd2565b8a.jpg)
![Uploading Screenshot_20210913_162012_com.guoshi.httpcanary.premium.jpg…]()

登陆保护关了也是一样，是url有问题吗，微博该怎么抓url

**Comment by Hellager** [comment]
用手机端的 **微博国际版** 抓包
在 **我的** 里找到 **关注的超话** 点进去
然后开启抓包下拉刷新一下 在抓到的包里面直接搜**gsid**然后复制找到的链接就行 或者在抓到的包里找到/2/cardlist这一项 复制请求链接

**Comment by angelas1qiaolezi** [comment]
![image](https://user-images.githubusercontent.com/90556379/133094393-0382469b-6714-4487-b58f-fbf7d554aba1.png)
我用虚拟机抓到了，但还是运行出问题，难受

**Comment by angelas1qiaolezi** [comment]
![VYLWBXRWXYGHNPK%}I8L8TY](https://user-images.githubusercontent.com/90556379/133099003-51b84a5c-cc9a-470e-8b56-c5c4491041a9.jpg)
终于成了，原来必须要微博国际版才可以啊。但还是有一个问题，我运行完，只能签到一部分，然后手动签到提示我系统繁忙，然后就出验证了，需解了之后才能继续签，怎样解决？

**Comment by Hellager** [comment]
supertopicsign.py 154行
`time.sleep(random.randint(0, 5))`
把这里的随机时间区间改大 `time.sleep(random.randint(15, 30))`这种
如果还是系统繁忙可以用SIGN_LIST把超话分批签到 隔段时间签一批

**Comment by angelas1qiaolezi** [comment]
今天又不行了，云函数跟action都报一样的错：
**{"errorCode":1,"errorMessage":"user code exception caught","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 6, in main_handler\n    follow_list = supertopic.get_follow_list()\n  File \"/var/user/supertopicsign.py\", line 83, in get_follow_list\n    card_group = response.json().get('cards', [{}])[0].get('card_group', [])\nIndexError: list index out of range","statusCode":430}**

END RequestId:4db20c46-a3ab-44a7-a4f2-92c1ba4152d4

Report RequestId:4db20c46-a3ab-44a7-a4f2-92c1ba4152d4 Duration:26791ms Memory:128MB MemUsage:52.406250MB

**Comment by Hellager** [comment]
我重新改了一下 用我现在仓库里的 supertopicsign.py 替换你的仓库里的同名文件 试试看
然后云函数用的zip在我仓库的 README.md更新了 是1.0.3版本
