### ISSUE TITLE
青龙面板运行的话cookie在哪抓呢？

### ISSUE THREAD

**Issue by forchannot** [Hellager/weibo_supertopic_sign#11]
我在电脑上抓的网页版cookie提示这个·
![image](https://user-images.githubusercontent.com/100580891/175769430-62869369-3e8b-4685-8a9b-c40d19b89fb2.png)

**Comment by Hellager** [comment]
用手机端的微博国际版去抓，更新了下README.md，之前是有说明的，莫名掉了

**Comment by Hellager** [comment]
或者看看这个 issue 里的 https://github.com/Hellager/weibo_supertopic_sign/issues/3

**Comment by forchannot** [comment]
> 用手机端的微博国际版去抓，更新了下README.md，之前是有说明的，莫名掉了

![Screenshot_2022-06-25-18-40-35-027_com guoshi htt](https://user-images.githubusercontent.com/100580891/175770078-10ee84d0-3f92-4418-b923-35a9b4e11514.jpg)
![Screenshot_2022-06-25-18-40-31-922-edit_com guosh](https://user-images.githubusercontent.com/100580891/175770080-6dda179a-fa84-472b-a2bf-d1acd4508b3a.jpg)
用微博国际版抓搜cardlist只搜出来这几个，但是这个几个url都一样，还是不行

**Comment by forchannot** [comment]
> 用手机端的微博国际版去抓，更新了下README.md，之前是有说明的，莫名掉了

我的问题，抓错了，现在好了，感谢

**Comment by forchannot** [comment]
> 用手机端的微博国际版去抓，更新了下README.md，之前是有说明的，莫名掉了

顺便就在这问一下，不开新issue了，青龙面板怎么单独关闭该脚本的通知，同级目录下我有其他的脚本需要通知，想要关闭这个的通知，用什么环境变量呢？我试了试Sign_WeiboNotify=0不行

**Comment by Hellager** [comment]
> > 用手机端的微博国际版去抓，更新了下README.md，之前是有说明的，莫名掉了
> 
> 
> 
> 顺便就在这问一下，不开新issue了，青龙面板怎么单独关闭该脚本的通知，同级目录下我有其他的脚本需要通知，想要关闭这个的通知，用什么环境变量呢？我试了试Sign_WeiboNotify=0不行

程序里面的结果的通知？注释掉345行
```
//notifier.sendNotify(title, content, {}, '');

```

**Comment by forchannot** [comment]
> > > 用手机端的微博国际版去抓，更新了下README.md，之前是有说明的，莫名掉了
> > 
> > 
> > 顺便就在这问一下，不开新issue了，青龙面板怎么单独关闭该脚本的通知，同级目录下我有其他的脚本需要通知，想要关闭这个的通知，用什么环境变量呢？我试了试Sign_WeiboNotify=0不行
> 
> 程序里面的结果的通知？注释掉345行
> 
> ```
> //notifier.sendNotify(title, content, {}, '');
> ```

好的，感谢
