### ISSUE TITLE
想问一下 如果关注的超话比较多 即使把超时都设置最高也无法签到完是吗？

### ISSUE THREAD

**Issue by jiuchu** [Hellager/weibo_supertopic_sign#14]
我数了下 只签到了30个左右。然后也没有发推送 用本地运行可以全部签到完也会发推送 大概20多分钟

**Comment by Hellager** [comment]
超时设置最高是什么意思？python 的云函数版本？这部分限制原因是云函数自身超时限制，想全签的话可以拆成几个分批运行，在设置里设置仅签到给出的超话就行
如果是挂青龙面板的话不应该出现这个问题，实测签170+没问题
可以发日志看看

**Comment by jiuchu** [comment]
> 超时设置最高是什么意思？python 的云函数版本？这部分限制原因是云函数自身超时限制，想全签的话可以拆成几个分批运行，在设置里设置仅签到给出的超话就行 如果是挂青龙面板的话不应该出现这个问题，实测签170+没问题 可以发日志看看

嗯嗯，没表达清楚，是云函数运行的，拆成几个分批运行，这个不知道咋设置。。大佬能给个图示意下吗，感谢，关注了一百多超话，刚刚在手动取关，实在麻烦..

**Comment by jiuchu** [comment]
> 超时设置最高是什么意思？python 的云函数版本？这部分限制原因是云函数自身超时限制，想全签的话可以拆成几个分批运行，在设置里设置仅签到给出的超话就行 如果是挂青龙面板的话不应该出现这个问题，实测签170+没问题 可以发日志看看
大佬的意思是多创建几个云函数运行是这个意思吗？

**Comment by jiuchu** [comment]
> 超时设置最高是什么意思？python 的云函数版本？这部分限制原因是云函数自身超时限制，想全签的话可以拆成几个分批运行，在设置里设置仅签到给出的超话就行 如果是挂青龙面板的话不应该出现这个问题，实测签170+没问题 可以发日志看看



大佬的意思是多创建几个云函数运行是这个意思吗？

**Comment by Hellager** [comment]
```JSON
{
  "SIGN_TYPE": "ONLY",
  "SIGN_LIST": "超话名称1;超话名称2;超话名称3"
}
```
主要是这两个参数，别的正常填就行，这样设置就只会签到 超话名称1、2、3，第一次设置会比较麻烦
有条件的话还是推荐挂个青龙面板
安卓手机会折腾的话也可以自己下个 Termux 搭个 nodejs 环境，然后跑
可以参考这个  https://github.com/NobyDa/Script/issues/173

**Comment by Hellager** [comment]
> > 超时设置最高是什么意思？python 的云函数版本？这部分限制原因是云函数自身超时限制，想全签的话可以拆成几个分批运行，在设置里设置仅签到给出的超话就行 如果是挂青龙面板的话不应该出现这个问题，实测签170+没问题 可以发日志看看
> 
> 大佬的意思是多创建几个云函数运行是这个意思吗？

对，就是设置的时候会比较麻烦，而且会分批通知

**Comment by jiuchu** [comment]
> ```json
> {
>   "SIGN_TYPE": "ONLY",
>   "SIGN_LIST": "超话名称1;超话名称2;超话名称3"
> }
> ```
> 
> 主要是这两个参数，别的正常填就行，这样设置就只会签到 超话名称1、2、3，第一次设置会比较麻烦 有条件的话还是推荐挂个青龙面板 安卓手机会折腾的话也可以自己下个 Termux 搭个 nodejs 环境，然后跑 可以参考这个 [NobyDa/Script#173](https://github.com/NobyDa/Script/issues/173)


好的感谢大佬，暂时没时间研究别的，我先取关一些没用的超话吧，看看一次最多签到多少个。云函数是只有签到完才会推送吗？因为我下午没签到完就没有收到推送，有点疑惑想确认一下。

**Comment by Hellager** [comment]
准确来说是执行完再签到，程序流程是先获取超话列表，然后根据设置的规则提取出要签到的列表，然后执行签到操作，你可以看看日志是在哪里卡住了

**Comment by jiuchu** [comment]
> 准确来说是执行完再签到，程序流程是先获取超话列表，然后根据设置的规则提取出要签到的列表，然后执行签到操作，你可以看看日志是在哪里卡住了

刚刚手动执行失败了 日志如下
count=20 HTTP/1.1" 200 None

page 4 get data success

Starting new HTTPS connection (1): api.weibo.cn:443

https://api.weibo.cn:443 "GET /2/cardlist?aid=01A8mcrguKx8FJmCaDVVkUhHjRvXALVG8fOYCU8dhyBYbvuiA.&c=weicoabroad&containerid=100803_-_followsuper&extparam=&from=1299295010&gsid=_2A25P-xziDeRxGeRP6FQQ9ijOzziIHXVqkRcqrDV6PUJbkdANLXLjkWpNUCimGo8VyHSmJ0XbJ7w7spqbz9o7N1oe&i=b7cd3c5&lang=zh_CN&page=1&s=ffffffff&ua=MuMu_6.0.1_WeiboIntlAndroid_4210&v_f=5&v_p=72&since_id=%7B%22manage%22%3A%22%22%2C%22follow%22%3A%221022%3A100808852d3ea07ccd72c3d32b3e52cfe2db75%22%2C%22page%22%3A5%7D&source=4215535043&wm=2468_1001&count=20 HTTP/1.1" 200 None

page 5 get data success

Starting new HTTPS connection (1): api.weibo.cn:443

https://api.weibo.cn:443 "GET /2/cardlist?aid=01A8mcrguKx8FJmCaDVVkUhHjRvXALVG8fOYCU8dhyBYbvuiA.&c=weicoabroad&containerid=100803_-_followsuper&extparam=&from=1299295010&gsid=_2A25P-xziDeRxGeRP6FQQ9ijOzziIHXVqkRcqrDV6PUJbkdANLXLjkWpNUCimGo8VyHSmJ0XbJ7w7spqbz9o7N1oe&i=b7cd3c5&lang=zh_CN&page=1&s=ffffffff&ua=MuMu_6.0.1_WeiboIntlAndroid_4210&v_f=6&v_p=72&since_id=%7B%22manage%22%3A%22%22%2C%22follow%22%3A%221022%3A1008086b5b74b70d024d16ef7eac0faabb7b6f%22%2C%22page%22%3A6%7D&source=4215535043&wm=2468_1001&count=20 HTTP/1.1" 200 None

ERROR RequestId: ac646e99-d721-4d83-acd1-dbc0d35f6424 Result: Traceback (most recent call last):   File "/var/user/index.py", line 6, in main_handler     follow_list = supertopic.get_follow_list()   File "/var/user/supertopicsign.py", line 83, in get_follow_list     card_group = response.json().get('cards', [{}])[0].get('card_group', []) IndexError: list index out of range

END RequestId: ac646e99-d721-4d83-acd1-dbc0d35f6424

Report RequestId: ac646e99-d721-4d83-acd1-dbc0d35f6424 Duration: 44523ms Memory: 128MB MemUsage: 16.65MB

**Comment by Hellager** [comment]
稳定复发吗？出现情况少的话出错后手动执行就行，比较稳定的话试试这样改
// supertopicsign.py  line83
```python
try:
            card_group = response.json().get('cards', [{}])[0].get('card_group', [])
            cardlistInfo = response.json().get('cardlistInfo', [{}])

            since_id = str(cardlistInfo["since_id"]
except:
            follow_list = [] # 加这句就是清空列表，到时候会看到发送的通知消息没内容，意味着出错了。不加就是签到已经获取的列表。再具体的错误处理流程我得好好想想怎么改
            break;

```

**Comment by jiuchu** [comment]
> 稳定复发吗？出现情况少的话出错后手动执行就行，比较稳定的话试试这样改 // supertopicsign.py line83
> 
> ```python
> try:
>             card_group = response.json().get('cards', [{}])[0].get('card_group', [])
>             cardlistInfo = response.json().get('cardlistInfo', [{}])
> 
>             since_id = str(cardlistInfo["since_id"]
> except:
>             follow_list = [] # 加这句就是清空列表，到时候会看到发送的通知消息没内容，意味着出错了。不加就是签到已经获取的列表。再具体的错误处理流程我得好好想想怎么改
>             break;
> ```

感谢大佬回复 现在用了别人的
