### ISSUE TITLE
为什么执行不完签到？

### ISSUE THREAD

**Issue by aka-kid** [Hellager/weibo_supertopic_sign#2]
我关注的超话数在70个左右，一般在签到20左右的时候，就会终止，设置初始化超时时间	300秒，执行超时时间900秒，日志如下：

麻烦您帮忙看看，谢谢

ERROR RequestId:bd03b7a7-b677-4a8d-9dc9-7eab412a8d07 Result:{"errorCode":-1,"errorMessage":"Invoking task timed out after 900 seconds","statusCode":433}

END RequestId:bd03b7a7-b677-4a8d-9dc9-7eab412a8d07

Report RequestId:bd03b7a7-b677-4a8d-9dc9-7eab412a8d07 Duration:900000ms Memory:512MB MemUsage:52.503906MB

**Comment by Hellager** [comment]
原因就是执行超时，这个是为了避免大量签到的时候网络请求过快被检测到后触发验证
300秒这个是因为我自己关注的超话只有二十几个，300秒正好够
解决方法：
1、把超时时间全都拉到最大看能不能全签完
2、修改以下程序段中的延时时间 过短可能会触发验证
supertopicsign.py 68行
`time.sleep(random.randint(5, 10))`
supertopicsign.py 154行
`time.sleep(random.randint(15, 30))`
3、用SIGN_TYPE参数把超话分批次签到
4、找一个超时时间超长的云服务 
比如自己服务器上定时执行 或者fork仓库后用Github Actions执行 这个超时时间我记得是六小时

**Comment by aka-kid** [comment]
用方法3解决了，谢谢
