### ISSUE TITLE
android版本的微博轻享版抓不到cardlist接口

### ISSUE THREAD

**Issue by LeoJwj** [Hellager/weibo_supertopic_sign#22]
电脑上能抓包吗？

**Comment by Hellager** [comment]
微博轻享版 6.0.3.1 + IOS Stream 抓包没问题
不建议在电脑上试，用模拟器很痛苦，也不一定行；win11 直接安装对应 apk + fiddler 也很烦，你得配一大堆东西，我都试过
你的问题有两个方向解决
1. 怀疑抓包软件问题 -> 替换抓包软件并保证开启了 HTTPS 抓包功能
2. 怀疑抓包操作有问题 -> 请根据文档抓包说明操作，大退微博轻享版，开启抓包并确保是 HTTPS，然后启动微博轻享版，刷新两下，再去关注的超话界面刷新两下，然后直接停止抓包，搜索域名 api.weibo.com 下 cardlist 关键词，查看响应结构体是否为包含超话列表，若是则可直接复制链接使用

或者你的账号十分幸运，是'天选之子'，就像 https://github.com/Hellager/weibo_supertopic_sign/issues/3 这个 issue 里，响应和别人完全不一样，那就得自己根据自己的返回结构体改程序了

**Comment by LeoJwj** [comment]
我最后安装了模拟器搞定了cookie。但是又有另一个问题。脚本直接没报错，但是没有签到。
![Screenshot_2022-12-07-23-56-58-550_com mmbox xbrowser](https://user-images.githubusercontent.com/8219834/206227771-0531df72-8ae0-47f2-9f82-44eddf63c9d6.jpg)
![Screenshot_2022-12-07-23-56-07-953_com hengye share](https://user-images.githubusercontent.com/8219834/206227800-322bbf76-6802-45e7-8ca9-011a65b5fc3a.jpg)

**Comment by LeoJwj** [comment]
@Hellager 看日志是没有获取到超话列表数据？

**Comment by Hellager** [comment]
更像是成为了天选之人需要验证，添加以下两句打印，第一句有原神说明数据获取没问题，第二句有问题说明你真的是天选之人需要验证
```js
// Sign_Weibo.js line 267
console.log(topic_lis)

// Sign_Weibo.js line 267
console.log(res_obj)
```

Android 记得最好把 headers 改成你自己抓包获取的 headers，基本上就是改个 User-Agent
```js
// Sign_Weibo.js line 150
    const request_username_headers = {
        'Accept': '*/*',
        'Host': 'api.weibo.cn',
        'Accept-Encoding': 'gzip, deflate, br',
        'Accept-Language': 'zh-Hans-CN;q=1, en-CN;q=0.9',
        'User-Agent': 'WeiboOverseas/4.7.8 (iPhone; iOS 15.5; Scale/3.00)',
        'Content-type': 'application/x-www-form-urlencoded',
    };
```

**Comment by LeoJwj** [comment]
![image](https://user-images.githubusercontent.com/8219834/206338564-e381029b-d8e8-47df-9225-28df5b1e9bef.png)
@Hellager 列表是抓到了，签到失败了？

**Comment by LeoJwj** [comment]
我手动先签到一个超话，然后跑脚本就成功了
![image](https://user-images.githubusercontent.com/8219834/206346641-5e6f02ba-5d14-4a8a-b161-0cc62273e7e0.png)

**Comment by Hellager** [comment]
那挺好的，可能是因为以前从来没用过国际版的影响，我更新下说明
