### ISSUE TITLE
微博国际版cookie错误 

### ISSUE THREAD

**Issue by lazybabyz** [Hellager/weibo_supertopic_sign#23]
请教一下大佬，应该是找哪一个路径下面的
感谢回复

## 开始执行... 2022-12-27 10:31:08

2022-12-27 10:31:08 info 微博超话签到脚本开始执行
2022-12-27 10:31:09 error 获取用户名失败, 错误提示：校验参数不存在
2022-12-27 10:31:09 info 当前微博用户: undefined
2022-12-27 10:31:09 info 开始获取超话列表
2022-12-27 10:31:22 info 获取超话列表第 1 页数据失败, 错误提示：校验参数不存在
2022-12-27 10:31:22 warning 无待签到列表

## 执行结束... 2022-12-27 10:31:22  耗时 14 秒
![微信图片_20221227104225](https://user-images.githubusercontent.com/56071946/209602800-c6ca93b8-1b62-4e3a-8cf5-ba376bcfaff4.png)

![微信图片_20221227102811](https://user-images.githubusercontent.com/56071946/209602451-dadfba36-eb6d-4ffb-be9f-b1bf0f09c6d0.jpg)
![微信图片_20221227103320](https://user-images.githubusercontent.com/56071946/209602457-d5eb01c3-7306-4a4e-952c-7e65aceef403.jpg)

**Comment by Hellager** [comment]
域名应该是 api.weibo.com
按教程来，在 **超话列表** 下来刷新后马上退出然后停止抓包，然后搜索 cardlist2，找到对应请求再复制对应 Cookie

**Comment by lazybabyz** [comment]
> 域名应该是 api.weibo.com 按教程来，在 **超话列表** 下来刷新后马上退出然后停止抓包，然后搜索 cardlist2，找到对应请求再复制对应 Cookie
 Cookie是 https://api.weibo.cn/2/cardlist?c=*************
