### ISSUE TITLE
签到有验证码怎么破？

### ISSUE THREAD

**Issue by zdbpython** [Hellager/weibo_supertopic_sign#26]
怀疑是微博风控，已使用4天，在第二天出现了一次超话签到需要过验证码，
能不能做个过验证码的脚本

**Comment by zdbpython** [comment]
用的是青龙面板，nodejs分支的那个

**Comment by Hellager** [comment]
我没触发过所以没办法做测试然后修改 orz，或者试试这个 [基于Chrome插件的微博超话自动签到](https://blog.csdn.net/qq_40140889/article/details/117744753?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522168156091416800227446208%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=168156091416800227446208&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_ecpm_v1~rank_v31_ecpm-2-117744753-null-null.142^v83^wechat,239^v2^insert_chatgpt&utm_term=chrome%20%E5%BE%AE%E5%8D%9A%20%E7%AD%BE%E5%88%B0&spm=1018.2226.3001.4187) ？
