### ISSUE TITLE
只签到第一页的超话且没有通知

### ISSUE THREAD

**Issue by kirito12827** [Hellager/weibo_supertopic_sign#28]
这是为什么😳
![IMG_20230615_001233](https://github.com/Hellager/weibo_supertopic_sign/assets/129661616/d3d2d1dc-2303-46d8-9bb1-36c59242b58b)

**Comment by Hellager** [comment]
只签一页可能是因为有些超话你今天已经签过了，后面这个是取值遇到问题了
具体原因用项目 test 目录下的程序本地跑一边测试看看
