### ISSUE TITLE
腾讯云函数执行的时候返回200 none

### ISSUE THREAD

**Issue by zopargr** [Hellager/weibo_supertopic_sign#4]
![image](https://user-images.githubusercontent.com/45194744/154791962-71f4323f-b990-4e1a-a2a0-9e0ceefc3c10.png)

**Comment by zopargr** [comment]
![image](https://user-images.githubusercontent.com/45194744/154792314-a6124b20-260f-47bf-a4bc-098e7bc66423.png)
在serverchan里返回的日志是这样的

**Comment by Hellager** [comment]
不好意思 我用自己的账号试了几次都没复现出来 
不过我更新了一下仓库 你现在可以把代码下载到本地 然后填写好 test 目录中 config.json 文件
接着运行 test_index.py 进行测试 所有数据将会保存到 data 目录中 你可以看看是哪个环节出现了错误
有所发现的话请更新下进展 我也好奇是哪里出问题

**Comment by zopargr** [comment]
已经解决了，我把微博的密码改了，它就可以签到成功了，推测是微博意识到访问异常
