### ISSUE TITLE
请问这个脚本现在可以正常工作吗？

### ISSUE THREAD

**Issue by 3dian** [Hellager/weibo_supertopic_sign#5]
前天我用charles抓包到完整的url，并且全部签到了。
今天再测试的时候，就发现前几个可以正常签到成功，后面就会返回这样的签到错误

{"result":0,"scheme":"https:\/\/passport.weibo.cn\/verify\/index?id=2NzFiIal3AANID1BZQcpAPL560SUhUrfyC3N1cGVyX3RvcGlj"}
{"result":0,"msg":"系统繁忙，请稍后重试！(402003)"}

**Comment by Hellager** [comment]
这可能是请求太快了 被检测到是程序在运行 适当拉大随机时间间隔就行
