### ISSUE TITLE
感谢大佬的程序！有不会弄的朋友可以问我！

### ISSUE THREAD

**Issue by HaodongZou** [Hellager/weibo_supertopic_sign#7]
我用QuantumultX抓的包，然后运行在我的云服务器上，配置了自动脚本。腾讯云函数和GitHub Action都不太靠谱，因为有限制和IP异常等问题，还是本地或者在服务器上运行比较好。

如果需要的话我可以帮忙挂在我的服务器上（闲着也是闲着qwq）

**Comment by LeoJwj** [comment]
你好请问一下，你用的微博国际版是哪个版本的，我试了好几个版本都没有cardlist接口
