### ISSUE TITLE
程序正常运行，能获取超话列表，可是没有执行签到

### ISSUE THREAD

**Issue by jokerchen54** [Hellager/weibo_supertopic_sign#8]
![screenshot-20220621-170843](https://user-images.githubusercontent.com/41314025/174762832-025ab01a-41e5-46d2-9718-b917de4866e0.png)
如图，日志正常打印获取数据日志，可是没有执行签到，等程序跑完后，去微博看确实没有签到成功

**Comment by Hellager** [comment]
vim 查看目录下的 ./data/handled_follow_list.json 文件，查看 sign_action 参数，可能是这部分缺失。
确定缺失的话继续查看 ./data/row_follow_list.json, 看看是否原始获得的数据就是缺失的

**Comment by jokerchen54** [comment]
![222](https://user-images.githubusercontent.com/41314025/174765053-c1d12c6e-c50d-4ea3-a83f-fb188b0a7cc3.png)
查看了两个文件，数据均没有缺失

**Comment by Hellager** [comment]
test_do_sign_tasks.py 
Line 70   response = requests.post(sign_url, headers=headers, data=sign_params)
在下面加个 print(response.json()) 看看结果是什么

**Comment by jokerchen54** [comment]
![333](https://user-images.githubusercontent.com/41314025/174767268-933a09c3-661c-4f70-b76e-5229135f9b3c.png)

**Comment by jokerchen54** [comment]
![image](https://user-images.githubusercontent.com/41314025/174771208-c86118af-c8e3-40b3-8f3a-5abad2c7aab2.png)
since_id的值为空，不知道影不影响

**Comment by jokerchen54** [comment]
![image](https://user-images.githubusercontent.com/41314025/174773043-574ff3e4-497a-4ea6-9386-963ec5df4a50.png)
我自己上去微博签到了一个超话，进行了人工认证后，程序可以正常运行了

**Comment by Hellager** [comment]
ok，估计是验证方面的问题
